services:
  esocial_docs:
    build:
      context: ${COMPOSE_CONTEXT:-https://github.com/jbsanf/esocial_doc_webscraping.git}
      dockerfile: Dockerfile
      tags:
        - esocial_docs:latest
    container_name: esocial_docs_bot
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      API_TOKEN:
      POSTGRES_HOST: ${POSTGRES_HOST:-esocial_docs_db}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
    image: esocial_docs:latest
    networks:
      - esocialdocs
    restart: unless-stopped
    volumes:
      - esocialdocs:/data
  postgres:
    container_name: esocial_docs_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    image: postgres:12.15-alpine3.18
    networks:
      - esocialdocs
    ports:
      - "15432:${POSTGRES_PORT:-5432}"
    restart: unless-stopped
    volumes:
       - esocialdocs:/data

networks:
  esocialdocs:
    name: esocialdocs
    driver: bridge

volumes:
  esocialdocs:
    name: "esocialdocs"